#debug: true

logging:
  level:
    de.workshops.bookshelf: DEBUG
    org.springframework: INFO

app:
  name: Bookshelf

springdoc:
  api-docs:
    enabled: true

swagger:
  title: Bookshelf API
  description: Bookshelf API
  version: v1.0.0
  capacity: 2000
  license:
    name: 'MIT License'
    url: 'https://opensource.org/licenses/MIT'
  blabla: lksjdfglkdsjg

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: birgit
    password: geheim
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
#    generate-ddl: true
#    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"